nav:
  - 首页: index.md
  - Mouse Away: 
    - Win+R: ./win+r+cli/win+r.md
    - CLI: ./win+r+cli/cli.md
  - CLI Tools:
    - Shell 脚本: ./cli_script_tool/script.md
    - 常用工具: ./cli_script_tool/tools.md
  - Custom Env:
    - 集成编辑器: ./custom_env/ide.md
  - Mark Lan:
    - Markdown: ./md_tex_typ/md.md
  - Repo & Remote:
    - 搭建仓库: ./repo_remote/repo.md
  - Personal Web:
    - 搭建网站: ./personal_website/web.md

site_name: 星中观潮の小站
site_url: https://starringtide.github.io/starringtide-web/
theme:
  name: material
  language: 'zh'
  favicon: assets/icons/favicon.png
  icon:
    logo: material/notebook-outline
    top: material/arrow-up-thin
  features:
    - navigation.footer # 允许页脚导航
    - navigation.tabs # 允许标签导航
    - navigation.tabs.sticky # 允许标签导航固定
    - navigation.sections # 允许章节导航
    - navigation.path # 允许路径导航(形如 Home > Details)
    - navigation.top # 允许返回顶部
    - navigation.instant 
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: teal
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
      primary: blue
      accent: orange

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true # 允许使用通用的数学公式
  - attr_list
  - md_in_html

use_directory_urls: false
plugins:
  - search: 
      lang: [zh, en]
      # separator: '[\s\-,:!=\[\]()"/]+|(?<!\w)\.(?!\d)|&[lg]t;' # 分词器分词规则，"[\s\-,:!=\[\]()"/]+"为特殊分隔符，"(?<!\w)\.(?!\d)"为小数点分隔符，"&[lg]t;"为HTML转义字符
      jieba_dict:  # 自定义中文分词词典
  - statistics:
      words_per_minute: 200
  - minify:
      minify_html: true

extra_css:
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://cdn.jsdelivr.net/gh/kjartanhr/JetBrainsMono-Webfont@main/JetBrainsMono/JetBrainsMono.css
  - assets/css/custom.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:
  - assets/javascripts/color.js
  - assets/javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js